/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    properties: Property;
    blogs: Blog;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    'cf7-tracker': Cf7Tracker;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'cf7-tracker': Cf7TrackerSelect<false> | Cf7TrackerSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  homeHero?: {
    title?: string | null;
    description?: string | null;
    videoUrl?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  featuredPropertiesOverride?:
    | {
        name?: string | null;
        details?: string | null;
        image?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  timelessComfort?: {
    title?: string | null;
    description?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  whyChooseUs?:
    | {
        label?: string | null;
        heading?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  vrTour?: {
    title?: string | null;
    description?: string | null;
    bannerImage?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  concierge?: {
    title?: string | null;
    description?: string | null;
    image?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  newestResidences?: {
    title?: string | null;
    description?: string | null;
    youtubeUrl?: string | null;
    subscribeLink?: string | null;
  };
  homeContact?: {
    heading?: string | null;
    selectedForm?: (number | null) | Form;
  };
  propertiesPageHeader?: {
    title?: string | null;
    description?: string | null;
    sectionHeading?: string | null;
  };
  conciergePage?: {
    hero?: {
      title?: string | null;
      description?: string | null;
      bannerImage?: string | null;
    };
    services?: {
      heading?: string | null;
      items?:
        | {
            title?: string | null;
            icon?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    howItWorks?: {
      heading?: string | null;
      image?: string | null;
      steps?:
        | {
            stepNumber?: string | null;
            title?: string | null;
            description?: string | null;
            icon?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    whyLoveIt?: {
      heading?: string | null;
      cards?:
        | {
            tag?: string | null;
            description?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    contactForm?: {
      heading?: string | null;
      subheading?: string | null;
      selectedForm?: (number | null) | Form;
    };
  };
  aboutPage?: {
    storyTitle?: string | null;
    bannerImage?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    visionTitle?: string | null;
    visionText?: string | null;
    missionTitle?: string | null;
    missionText?: string | null;
    valuesTitle?: string | null;
    valuesText?: string | null;
    whyHeadingPrefix?: string | null;
    whyHeadingMain?: string | null;
    whySubtitle?: string | null;
    whyImage?: string | null;
    feature1?: string | null;
    feature2?: string | null;
    feature3?: string | null;
    feature4?: string | null;
    contactHeading?: string | null;
  };
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout?:
    | (InquiryHeroBlock | CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock | CarouselBlock)[]
    | null;
  privacyPolicyPage?: {
    title?: string | null;
    effectiveDate?: string | null;
    sections?:
      | {
          heading: string;
          content?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
  };
  termsAndConditionsPage?: {
    title?: string | null;
    subheading?: string | null;
    effectiveDate?: string | null;
    sections?:
      | {
          heading: string;
          content?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
  };
  buyAHomePage?: {
    title?: string | null;
    subheading?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    imageUrl?: string | null;
    additionalContent?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    selectedForm?: (number | null) | Form;
    formAction?: string | null;
    buttonText?: string | null;
  };
  otherInquiriesPage?: {
    title?: string | null;
    subheading?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    imageUrl?: string | null;
    additionalContent?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    selectedForm?: (number | null) | Form;
    formAction?: string | null;
    buttonText?: string | null;
  };
  tradeInquiryPage?: {
    title?: string | null;
    subheading?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    imageUrl?: string | null;
    additionalContent?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    selectedForm?: (number | null) | Form;
    formAction?: string | null;
    buttonText?: string | null;
  };
  thankYouPage?: {
    title?: string | null;
    subheading?: string | null;
    message?: string | null;
    additionalContent?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The primary keyword this page targets. Used to evaluate SEO quality.
     */
    focusKeyword?: string | null;
    /**
     * Override the canonical URL if this page has a preferred URL (leave blank to use the page URL).
     */
    canonicalUrl?: string | null;
    /**
     * Control how search engines index and follow this page.
     */
    metaRobots?: {
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      /**
       * Prevent search engines from showing a cached version.
       */
      noarchive?: boolean | null;
      /**
       * Prevent search engines from showing a text snippet in results.
       */
      nosnippet?: boolean | null;
    };
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  enableErpPush?: boolean | null;
  /**
   * Leave blank to use the global fallback URL in Settings.
   */
  frappeUrl?: string | null;
  apiMethod?: string | null;
  fieldMapping?:
    | {
        formField: string;
        frappeField: string;
        id?: string | null;
      }[]
    | null;
  staticFields?:
    | {
        frappeField: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * The primary keyword this page targets. Used to evaluate SEO quality.
     */
    focusKeyword?: string | null;
    /**
     * Override the canonical URL if this page has a preferred URL (leave blank to use the page URL).
     */
    canonicalUrl?: string | null;
    /**
     * Control how search engines index and follow this page.
     */
    metaRobots?: {
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      /**
       * Prevent search engines from showing a cached version.
       */
      noarchive?: boolean | null;
      /**
       * Prevent search engines from showing a text snippet in results.
       */
      nosnippet?: boolean | null;
    };
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'editor' | 'seo-editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InquiryHeroBlock".
 */
export interface InquiryHeroBlock {
  title?: string | null;
  subheading?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  selectedForm?: (number | null) | Form;
  formAction?: string | null;
  buttonText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'inquiryHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  title?: string | null;
  slides: {
    image: number | Media;
    heading?: string | null;
    caption?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  status?: ('for_sale' | 'sold' | 'under_contract') | null;
  featured?: boolean | null;
  isGroupParent?: boolean | null;
  parentProperty?: (number | null) | Property;
  publishedAt?: string | null;
  bannerImages?: (number | Media)[] | null;
  name: string;
  address?: string | null;
  price?: string | null;
  description?: string | null;
  /**
   * Select the contact form to display in Section 6.
   */
  contactForm?: (number | null) | Form;
  propertySummary?: {
    numberOfBeds?: string | null;
    numberOfBaths?: string | null;
    acArea?: string | null;
    designTheme?: string | null;
  };
  brokerInformation?: {
    brokerName?: string | null;
    companyName?: string | null;
    brokerImage?: (number | null) | Media;
  };
  builderName?: string | null;
  architectName?: string | null;
  interiorDesignName?: string | null;
  featuresAndAmenities?: {
    propertyDetails?: {
      propertyType?: string | null;
      yearBuilt?: string | null;
      totalInteriorLivableArea?: string | null;
      lotSize?: string | null;
    };
    bedsAndBaths?: {
      beds?: string | null;
      baths?: string | null;
      numberOfFloors?: string | null;
    };
    interiorFeatures?: {
      firstFloor?: string | null;
      secondFloor?: string | null;
      thirdFloor?: string | null;
      additionalFeatures?: string | null;
    };
    exteriorFeatures?: {
      garage?: string | null;
      yard?: string | null;
      siding?: string | null;
      pool?: string | null;
      driveway?: string | null;
      roof?: string | null;
      deckPatio?: string | null;
    };
  };
  allPhotos?: (number | Media)[] | null;
  progressPhotos?: (number | Media)[] | null;
  allFloorPlanPhotos?: (number | Media)[] | null;
  floorPlans?:
    | {
        floorName: string;
        areaSize?: string | null;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  video?: {
    videoType?: ('youtube' | 'file') | null;
    youtubeUrl?: string | null;
    videoFile?: (number | null) | Media;
  };
  projectTeam?: {
    brokerName?: string | null;
    builderName?: string | null;
    architectName?: string | null;
    interiorDesignerName?: string | null;
  };
  aboutSection?: {
    aboutTitle?: string | null;
    aboutIntro?: string | null;
    aboutBackgroundImage?: (number | null) | Media;
    historyText?: string | null;
    lifestyleText?: string | null;
    neighborhoodText?: string | null;
  };
  neighborhoodAccordion?:
    | {
        title: string;
        distance?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  eleganceBanner?: {
    title?: string | null;
    description?: string | null;
  };
  meta?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 150–160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * The primary keyword this page targets. Used to evaluate SEO quality.
     */
    focusKeyword?: string | null;
    /**
     * Override the canonical URL if this page has a preferred URL (leave blank to use the page URL).
     */
    canonicalUrl?: string | null;
    /**
     * Control how search engines index and follow this page.
     */
    metaRobots?: {
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      /**
       * Prevent search engines from showing a cached version.
       */
      noarchive?: boolean | null;
      /**
       * Prevent search engines from showing a text snippet in results.
       */
      nosnippet?: boolean | null;
    };
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * The primary keyword this page targets. Used to evaluate SEO quality.
     */
    focusKeyword?: string | null;
    /**
     * Override the canonical URL if this page has a preferred URL (leave blank to use the page URL).
     */
    canonicalUrl?: string | null;
    /**
     * Control how search engines index and follow this page.
     */
    metaRobots?: {
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      /**
       * Prevent search engines from showing a cached version.
       */
      noarchive?: boolean | null;
      /**
       * Prevent search engines from showing a text snippet in results.
       */
      nosnippet?: boolean | null;
    };
  };
  /**
   * Automatically calculated from blog content on save (200 WPM).
   */
  readingTime?: number | null;
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  categories?: (number | Category)[] | null;
  relatedBlogs?: (number | Blog)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cf7-tracker".
 */
export interface Cf7Tracker {
  id: number;
  formId: number;
  formName: string;
  submitterName?: string | null;
  submitterEmail?: string | null;
  submitterPhone?: string | null;
  formData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mailStatus?: ('pending' | 'sent' | 'failed') | null;
  mailNote?: string | null;
  erpStatus?: ('pending' | 'success' | 'failed' | 'not_configured') | null;
  erpLeadId?: string | null;
  erpResponse?: string | null;
  retryCount?: number | null;
  lastRetryAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  erpStatus?: ('not_configured' | 'success' | 'failed') | null;
  erpLeadId?: string | null;
  erpResponse?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'cf7-tracker';
        value: number | Cf7Tracker;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  homeHero?:
    | T
    | {
        title?: T;
        description?: T;
        videoUrl?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  featuredPropertiesOverride?:
    | T
    | {
        name?: T;
        details?: T;
        image?: T;
        href?: T;
        id?: T;
      };
  timelessComfort?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  whyChooseUs?:
    | T
    | {
        label?: T;
        heading?: T;
        text?: T;
        id?: T;
      };
  vrTour?:
    | T
    | {
        title?: T;
        description?: T;
        bannerImage?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  concierge?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  newestResidences?:
    | T
    | {
        title?: T;
        description?: T;
        youtubeUrl?: T;
        subscribeLink?: T;
      };
  homeContact?:
    | T
    | {
        heading?: T;
        selectedForm?: T;
      };
  propertiesPageHeader?:
    | T
    | {
        title?: T;
        description?: T;
        sectionHeading?: T;
      };
  conciergePage?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              description?: T;
              bannerImage?: T;
            };
        services?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    id?: T;
                  };
            };
        howItWorks?:
          | T
          | {
              heading?: T;
              image?: T;
              steps?:
                | T
                | {
                    stepNumber?: T;
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
            };
        whyLoveIt?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    tag?: T;
                    description?: T;
                    id?: T;
                  };
            };
        contactForm?:
          | T
          | {
              heading?: T;
              subheading?: T;
              selectedForm?: T;
            };
      };
  aboutPage?:
    | T
    | {
        storyTitle?: T;
        bannerImage?: T;
        paragraph1?: T;
        paragraph2?: T;
        visionTitle?: T;
        visionText?: T;
        missionTitle?: T;
        missionText?: T;
        valuesTitle?: T;
        valuesText?: T;
        whyHeadingPrefix?: T;
        whyHeadingMain?: T;
        whySubtitle?: T;
        whyImage?: T;
        feature1?: T;
        feature2?: T;
        feature3?: T;
        feature4?: T;
        contactHeading?: T;
      };
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        inquiryHero?: T | InquiryHeroBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
      };
  privacyPolicyPage?:
    | T
    | {
        title?: T;
        effectiveDate?: T;
        sections?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
            };
      };
  termsAndConditionsPage?:
    | T
    | {
        title?: T;
        subheading?: T;
        effectiveDate?: T;
        sections?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
            };
      };
  buyAHomePage?:
    | T
    | {
        title?: T;
        subheading?: T;
        description?: T;
        image?: T;
        imageUrl?: T;
        additionalContent?: T;
        selectedForm?: T;
        formAction?: T;
        buttonText?: T;
      };
  otherInquiriesPage?:
    | T
    | {
        title?: T;
        subheading?: T;
        description?: T;
        image?: T;
        imageUrl?: T;
        additionalContent?: T;
        selectedForm?: T;
        formAction?: T;
        buttonText?: T;
      };
  tradeInquiryPage?:
    | T
    | {
        title?: T;
        subheading?: T;
        description?: T;
        image?: T;
        imageUrl?: T;
        additionalContent?: T;
        selectedForm?: T;
        formAction?: T;
        buttonText?: T;
      };
  thankYouPage?:
    | T
    | {
        title?: T;
        subheading?: T;
        message?: T;
        additionalContent?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        canonicalUrl?: T;
        metaRobots?:
          | T
          | {
              indexing?: T;
              following?: T;
              noarchive?: T;
              nosnippet?: T;
            };
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InquiryHeroBlock_select".
 */
export interface InquiryHeroBlockSelect<T extends boolean = true> {
  title?: T;
  subheading?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  selectedForm?: T;
  formAction?: T;
  buttonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  title?: T;
  slides?:
    | T
    | {
        image?: T;
        heading?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  status?: T;
  featured?: T;
  isGroupParent?: T;
  parentProperty?: T;
  publishedAt?: T;
  bannerImages?: T;
  name?: T;
  address?: T;
  price?: T;
  description?: T;
  contactForm?: T;
  propertySummary?:
    | T
    | {
        numberOfBeds?: T;
        numberOfBaths?: T;
        acArea?: T;
        designTheme?: T;
      };
  brokerInformation?:
    | T
    | {
        brokerName?: T;
        companyName?: T;
        brokerImage?: T;
      };
  builderName?: T;
  architectName?: T;
  interiorDesignName?: T;
  featuresAndAmenities?:
    | T
    | {
        propertyDetails?:
          | T
          | {
              propertyType?: T;
              yearBuilt?: T;
              totalInteriorLivableArea?: T;
              lotSize?: T;
            };
        bedsAndBaths?:
          | T
          | {
              beds?: T;
              baths?: T;
              numberOfFloors?: T;
            };
        interiorFeatures?:
          | T
          | {
              firstFloor?: T;
              secondFloor?: T;
              thirdFloor?: T;
              additionalFeatures?: T;
            };
        exteriorFeatures?:
          | T
          | {
              garage?: T;
              yard?: T;
              siding?: T;
              pool?: T;
              driveway?: T;
              roof?: T;
              deckPatio?: T;
            };
      };
  allPhotos?: T;
  progressPhotos?: T;
  allFloorPlanPhotos?: T;
  floorPlans?:
    | T
    | {
        floorName?: T;
        areaSize?: T;
        image?: T;
        id?: T;
      };
  video?:
    | T
    | {
        videoType?: T;
        youtubeUrl?: T;
        videoFile?: T;
      };
  projectTeam?:
    | T
    | {
        brokerName?: T;
        builderName?: T;
        architectName?: T;
        interiorDesignerName?: T;
      };
  aboutSection?:
    | T
    | {
        aboutTitle?: T;
        aboutIntro?: T;
        aboutBackgroundImage?: T;
        historyText?: T;
        lifestyleText?: T;
        neighborhoodText?: T;
      };
  neighborhoodAccordion?:
    | T
    | {
        title?: T;
        distance?: T;
        image?: T;
        id?: T;
      };
  eleganceBanner?:
    | T
    | {
        title?: T;
        description?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        canonicalUrl?: T;
        metaRobots?:
          | T
          | {
              indexing?: T;
              following?: T;
              noarchive?: T;
              nosnippet?: T;
            };
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  excerpt?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        focusKeyword?: T;
        canonicalUrl?: T;
        metaRobots?:
          | T
          | {
              indexing?: T;
              following?: T;
              noarchive?: T;
              nosnippet?: T;
            };
      };
  readingTime?: T;
  publishedAt?: T;
  authors?: T;
  categories?: T;
  relatedBlogs?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        canonicalUrl?: T;
        metaRobots?:
          | T
          | {
              indexing?: T;
              following?: T;
              noarchive?: T;
              nosnippet?: T;
            };
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cf7-tracker_select".
 */
export interface Cf7TrackerSelect<T extends boolean = true> {
  formId?: T;
  formName?: T;
  submitterName?: T;
  submitterEmail?: T;
  submitterPhone?: T;
  formData?: T;
  mailStatus?: T;
  mailNote?: T;
  erpStatus?: T;
  erpLeadId?: T;
  erpResponse?: T;
  retryCount?: T;
  lastRetryAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  enableErpPush?: T;
  frappeUrl?: T;
  apiMethod?: T;
  fieldMapping?:
    | T
    | {
        formField?: T;
        frappeField?: T;
        id?: T;
      };
  staticFields?:
    | T
    | {
        frappeField?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  erpStatus?: T;
  erpLeadId?: T;
  erpResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteIcon?: (number | null) | Media;
  headerLogo?: (number | null) | Media;
  siteUrl?: string | null;
  frappeUrl?: string | null;
  frappeApiKey?: string | null;
  /**
   * API secret corresponding to the API key
   */
  frappeApiSecret?: string | null;
  frappeApiMethod?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteIcon?: T;
  headerLogo?: T;
  siteUrl?: T;
  frappeUrl?: T;
  frappeApiKey?: T;
  frappeApiSecret?: T;
  frappeApiMethod?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'blogs';
          value: number | Blog;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}